### ISSUE TITLE
🚨 We won't be accepting PRs on updating collaboration documentation ... for now

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/docs#14]
We are in the middle of reworking the UI a bit for collaboration.  While our collaboration documentation might be a bit outdated and could use some work, we would have to update them again pretty quickly after.  In order to avoid this extra work, we will just be skipping updating documentation on collaboration until this chunk of work is done.  When this issue is closed and unpinned, it can be assumed that we will be ready to accept PRs related to collaboration documentation.

Thanks

**Comment by iamnbutler** [comment]
Closing this, collaboration won't change much in the immediate future.
