### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by 0x2CA** [zed-industries/docs#24]

**Comment by iamnbutler** [comment]
Feel free to provide some additional info, otherwise this will be closed out. Thanks.

**Comment by 0x2CA** [comment]
internationalization

**Comment by iamnbutler** [comment]
As the editor current doesn't support internationalization I doubt we would start with the docs, as it adds more surface area for us to maintain. If someone is willing to take over maintaining the docs for certain languages we might consider this. The docs are open source with open collaboration, so feel free to add the PR you want to see.
