### ISSUE TITLE
it's typos in features page

### ISSUE THREAD

**Issue by skierpage** [zed-industries/docs#36]
I couldn't find a repo for https://zed.dev/features
> while keeping it's contents
> the top right of it's pane
> uses [Alacritty](https://github.com/alacritty/alacritty) as it's backend

None of these is an abbreviation of "it is" or "it has", so no apostrophe. ("Its" is already the possessive pronoun, just as you don't write "I like hi's editor.") Cheers.

**Comment by JosephTLyons** [comment]
Thanks @skierpage - appreciate it.
